source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!

def zyb_pods
    pod 'YYCategories','~> 1.0.4'
    pod 'YYModel','~> 1.0.4'
    pod 'WWBaseLib','~> 0.0.1'
    pod 'DTTableViewTool', :path => '../'
end

target 'DTTableViewToolExmaple' do
    zyb_pods
end

